-- +goose Up
ALTER TABLE beds
  DROP COLUMN IF EXISTS x,
  DROP COLUMN IF EXISTS y,
  DROP COLUMN IF EXISTS width,
  DROP COLUMN IF EXISTS height;

ALTER TABLE beds
  ADD COLUMN IF NOT EXISTS type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shape TEXT NOT NULL DEFAULT 'rectangle',
  ADD COLUMN IF NOT EXISTS sun_level TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS watering_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS length DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE beds
  DROP COLUMN IF EXISTS type,
  DROP COLUMN IF EXISTS shape,
  DROP COLUMN IF EXISTS sun_level,
  DROP COLUMN IF EXISTS watering_type,
  DROP COLUMN IF EXISTS width,
  DROP COLUMN IF EXISTS length,
  DROP COLUMN IF EXISTS height;

ALTER TABLE beds
  ADD COLUMN IF NOT EXISTS x DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS y DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION NOT NULL DEFAULT 0;
